/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    branches: Branch;
    categories: Category;
    'part-types': PartType;
    makes: Make;
    models: Model;
    brands: Brand;
    guides: Guide;
    enquiries: Enquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    branches: BranchesSelect<false> | BranchesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'part-types': PartTypesSelect<false> | PartTypesSelect<true>;
    makes: MakesSelect<false> | MakesSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The branch directory. Adding a record here creates its page, adds it to the finder and plots it on the network map. Nothing else needs changing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  /**
   * Used in the URL: /branches/your-slug
   */
  slug: string;
  province:
    | 'Gauteng'
    | 'Limpopo'
    | 'Mpumalanga'
    | 'North West'
    | 'Free State'
    | 'KwaZulu-Natal'
    | 'Eastern Cape'
    | 'Western Cape'
    | 'Northern Cape'
    | 'Pan-Africa';
  country: string;
  address: string;
  phone: string;
  /**
   * Leave blank to reuse the phone number.
   */
  whatsapp?: string | null;
  /**
   * Leave blank if this branch has no public email yet.
   */
  email?: string | null;
  hours?: string | null;
  /**
   * Decimal latitude, e.g. -26.2124
   */
  lat: number;
  /**
   * Decimal longitude, e.g. 28.2617
   */
  lng: number;
  /**
   * Uncheck to hide the branch without deleting its record.
   */
  active?: boolean | null;
  /**
   * Optional branch photograph.
   */
  photo?: (number | null) | Media;
  /**
   * Optional line shown on the branch page, e.g. "Counter and trade desk. Bulk collections by arrangement."
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the picture, for screen readers and for search. "Counter team checking a part number at the Boksburg branch", not "image".
   */
  alt: string;
  /**
   * Photographer credit, if one is required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The 13 parts systems. Each one publishes a page at /parts/[slug] listing its part types.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  label: string;
  /**
   * URL: /parts/your-slug
   */
  slug: string;
  /**
   * One line. Used on the homepage tile and the parts index.
   */
  blurb: string;
  /**
   * The answer-first opening, one or two sentences. Written so it makes sense quoted on its own, because this is what an answer engine lifts. Also used as the meta description.
   */
  summary: string;
  /**
   * Two or three paragraphs of genuine editorial.
   */
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * These publish as FAQ structured data, which is how assistants and featured snippets quote the site. Write the answer as a complete sentence that stands on its own.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Phosphor icon name, e.g. Disc, Engine, Funnel. See phosphoricons.com.
   */
  icon: string;
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual part types, e.g. Brake Pads or Clutch Kits. Each publishes its own page and feeds every vehicle page that lists it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "part-types".
 */
export interface PartType {
  id: number;
  label: string;
  /**
   * URL: /parts/[category]/your-slug
   */
  slug: string;
  category: number | Category;
  /**
   * The form that reads naturally mid-sentence: "needs a new clutch kit", "needs a new set of brake pads". Used to build headings on the vehicle pages, so getting it right is what stops those pages sounding machine-written.
   */
  singular: string;
  /**
   * Answer-first definition, one or two sentences. Start with the part name: "Brake pads are the replaceable friction blocks that...". This is the sentence an assistant will quote and the meta description.
   */
  summary: string;
  /**
   * What the component does within its system.
   */
  role: string;
  /**
   * Signs it is failing, written the way a driver would notice them rather than in workshop terms. Lists are the format snippets lift.
   */
  symptoms?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When it is normally replaced. Be honest where there is no fixed interval.
   */
  interval: string;
  /**
   * What the counter needs confirmed before the order is placed.
   */
  checks?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Publishes as FAQ structured data. Every question here is also shown on the page, which Google requires.
   */
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vehicle makes. Each publishes a page at /vehicles/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes".
 */
export interface Make {
  id: number;
  label: string;
  /**
   * URL: /vehicles/your-slug
   */
  slug: string;
  /**
   * Answer-first opening naming the make and the models covered. Used as the meta description.
   */
  summary: string;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vehicle models. Each publishes a page at /vehicles/[make]/[slug], plus one page per linked part type.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  label: string;
  /**
   * URL: /vehicles/[make]/your-slug
   */
  slug: string;
  make: number | Make;
  /**
   * e.g. Hatchback, Pickup, Panel van
   */
  body: string;
  /**
   * Answer-first opening naming the make, model and what it is. Used as the meta description.
   */
  summary: string;
  /**
   * The year and engine table. This is how a search including a model year is matched without needing a separate page for every year.
   */
  generations: {
    /**
     * e.g. 2011 to 2017, or 2017 onward
     */
    years: string;
    /**
     * e.g. 1.2, 1.4 and 1.6 petrol
     */
    engines: string;
    /**
     * Optional note for this generation.
     */
    note?: string | null;
    id?: string | null;
  }[];
  /**
   * Each part type linked here publishes a page at /vehicles/[make]/[model]/[part-type]. Add the components genuinely replaced on this vehicle, not everything in the catalogue.
   */
  parts: (number | PartType)[];
  /**
   * A general observation about this vehicle, true no matter which part is being bought. Shown on the model page and on every part page for it. Keep anything part-specific out of here and use the field below.
   */
  note?: string | null;
  /**
   * Observations tied to one specific part on this vehicle, shown only on that part page. This is the highest-value field on the site: it is the one sentence a competitor cannot template, and it is what makes each page genuinely worth ranking.
   */
  partNotes?:
    | {
        partType: number | PartType;
        note: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The nine private-brand lines plus the OEM option. Upload an official vector mark to replace the typographic plate the site renders by default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  label: string;
  slug: string;
  tier: 'private' | 'oem';
  /**
   * One line describing what the line covers.
   */
  note: string;
  /**
   * Official SVG or PNG logo. Until one is supplied the site renders a typographic plate rather than inventing a mark.
   */
  mark?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The site’s blog — trade guides and fitment notes. These are the pages that bring workshop searches in, so write them for the person at the car.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  /**
   * Two sentences maximum. Used on the index card and as the search description.
   */
  excerpt: string;
  category: 'Ordering' | 'Fitment' | 'Buying' | 'Trade' | 'Network';
  publishedAt: string;
  image?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Links the guide back to a catalogue system.
   */
  relatedCategory?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Trade, branch and part enquiries submitted through the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  type: 'wholesale' | 'branch' | 'general' | 'distributor';
  name: string;
  company?: string | null;
  email: string;
  phone: string;
  /**
   * Province, country or territory.
   */
  region?: string | null;
  /**
   * Rough monthly buying volume.
   */
  monthlySpend?: string | null;
  message: string;
  /**
   * Set when the enquiry came from a branch page.
   */
  branch?: (number | null) | Branch;
  /**
   * Part number, when the enquiry came from a part page.
   */
  part?: string | null;
  status?: ('new' | 'contacted' | 'routed' | 'closed') | null;
  /**
   * Page the form was on.
   */
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'part-types';
        value: number | PartType;
      } | null)
    | ({
        relationTo: 'makes';
        value: number | Make;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  province?: T;
  country?: T;
  address?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  hours?: T;
  lat?: T;
  lng?: T;
  active?: T;
  photo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  blurb?: T;
  summary?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  icon?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "part-types_select".
 */
export interface PartTypesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  category?: T;
  singular?: T;
  summary?: T;
  role?: T;
  symptoms?:
    | T
    | {
        text?: T;
        id?: T;
      };
  interval?: T;
  checks?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes_select".
 */
export interface MakesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  summary?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  make?: T;
  body?: T;
  summary?: T;
  generations?:
    | T
    | {
        years?: T;
        engines?: T;
        note?: T;
        id?: T;
      };
  parts?: T;
  note?: T;
  partNotes?:
    | T
    | {
        partType?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  tier?: T;
  note?: T;
  mark?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  publishedAt?: T;
  image?: T;
  body?: T;
  relatedCategory?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  region?: T;
  monthlySpend?: T;
  message?: T;
  branch?: T;
  part?: T;
  status?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Head office contact details, social links and the group figures shown across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  headOfficeName: string;
  email: string;
  phone?: string | null;
  address: string;
  /**
   * What gets sent to Google Maps for directions.
   */
  mapQuery: string;
  hours?: string | null;
  /**
   * Published Parts-Mall Corporation figures. Do not add a number that cannot be sourced.
   */
  corporateFacts?:
    | {
        value: string;
        label: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year: string;
        event: string;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Where new site enquiries are notified.
   */
  enquiryEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  headOfficeName?: T;
  email?: T;
  phone?: T;
  address?: T;
  mapQuery?: T;
  hours?: T;
  corporateFacts?:
    | T
    | {
        value?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        year?: T;
        event?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  enquiryEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}